// <auto-generated />
using System;
using ComptabiliteAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ComptabiliteAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250503123648_AddtestringNumfacture")]
    partial class AddtestringNumfacture
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ComptabiliteAPI.Models.Abonnement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Abonnements");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.Bilan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActifTotal")
                        .HasColumnType("numeric");

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PassifTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("EntrepriseId");

                    b.ToTable("Bilans");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.CompteBancaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateFermeture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOuverture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomBanque")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroCompte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Solde")
                        .HasColumnType("numeric");

                    b.Property<string>("TypeCompte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("ComptesBancaires");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.DeclarationCNSS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("integer");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MontantCotisation")
                        .HasColumnType("numeric");

                    b.Property<int>("NombreEmployes")
                        .HasColumnType("integer");

                    b.Property<string>("Periode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntrepriseId");

                    b.ToTable("DeclarationsCNSSes");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.DeclarationFiscale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("integer");

                    b.Property<int>("Etat")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontantTva")
                        .HasColumnType("numeric");

                    b.Property<string>("Periode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntrepriseId");

                    b.ToTable("DeclarationsFiscales");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.Depense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntreprisID")
                        .HasColumnType("integer");

                    b.Property<string>("Fournisseur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Justificatif")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Montant")
                        .HasColumnType("numeric");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Depenses");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.Devis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("numeric");

                    b.Property<int>("NumDevis")
                        .HasColumnType("integer");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("En attente");

                    b.HasKey("Id");

                    b.HasIndex("EntrepriseId");

                    b.ToTable("Devis");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.DevisDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DevisId")
                        .HasColumnType("integer");

                    b.Property<int>("ProduitServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DevisId");

                    b.HasIndex("ProduitServiceId");

                    b.ToTable("DevisDetails");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.Entreprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Identitegerant")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Justificatifedomicile")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Logo")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("MF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("RCS")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Entreprises");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.Facture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdressClient")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CinClient")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("integer");

                    b.Property<bool>("EstPayee")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("NomClient")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumFacture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("THT")
                        .HasColumnType("numeric");

                    b.Property<string>("TelClient")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntrepriseId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.FactureDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FactureId")
                        .HasColumnType("integer");

                    b.Property<decimal>("HT")
                        .HasColumnType("numeric");

                    b.Property<int>("ProduitServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.Property<decimal>("TTC")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FactureId");

                    b.HasIndex("ProduitServiceId");

                    b.ToTable("FactureDetails");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompteBancaireId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FactureId")
                        .HasColumnType("integer");

                    b.Property<string>("ModePaiement")
                        .HasColumnType("text");

                    b.Property<decimal>("Montant")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompteBancaireId");

                    b.HasIndex("FactureId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.ProduitService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TVA")
                        .HasColumnType("numeric");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntrepriseId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("ProduitServices");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AbonnementId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreeParId")
                        .HasColumnType("integer");

                    b.Property<int?>("DefaultEntrepriseId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AbonnementId");

                    b.HasIndex("CreeParId");

                    b.HasIndex("DefaultEntrepriseId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.Bilan", b =>
                {
                    b.HasOne("ComptabiliteAPI.Models.Entreprise", "Entreprise")
                        .WithMany()
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.CompteBancaire", b =>
                {
                    b.HasOne("ComptabiliteAPI.Models.Utilisateur", "Utilisateur")
                        .WithMany("ComptesBancaires")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.DeclarationCNSS", b =>
                {
                    b.HasOne("ComptabiliteAPI.Models.Entreprise", "Entreprise")
                        .WithMany()
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.DeclarationFiscale", b =>
                {
                    b.HasOne("ComptabiliteAPI.Models.Entreprise", "Entreprise")
                        .WithMany()
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.Depense", b =>
                {
                    b.HasOne("ComptabiliteAPI.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.Devis", b =>
                {
                    b.HasOne("ComptabiliteAPI.Models.Entreprise", "Entreprise")
                        .WithMany()
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.DevisDetail", b =>
                {
                    b.HasOne("ComptabiliteAPI.Models.Devis", "Devis")
                        .WithMany()
                        .HasForeignKey("DevisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComptabiliteAPI.Models.ProduitService", "ProduitService")
                        .WithMany()
                        .HasForeignKey("ProduitServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Devis");

                    b.Navigation("ProduitService");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.Entreprise", b =>
                {
                    b.HasOne("ComptabiliteAPI.Models.Utilisateur", "Utilisateur")
                        .WithMany("Entreprises")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.Facture", b =>
                {
                    b.HasOne("ComptabiliteAPI.Models.Entreprise", null)
                        .WithMany("Factures")
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComptabiliteAPI.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.FactureDetail", b =>
                {
                    b.HasOne("ComptabiliteAPI.Models.Facture", "Facture")
                        .WithMany("FactureDetails")
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComptabiliteAPI.Models.ProduitService", "ProduitService")
                        .WithMany()
                        .HasForeignKey("ProduitServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facture");

                    b.Navigation("ProduitService");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.Paiement", b =>
                {
                    b.HasOne("ComptabiliteAPI.Models.CompteBancaire", "CompteBancaire")
                        .WithMany()
                        .HasForeignKey("CompteBancaireId");

                    b.HasOne("ComptabiliteAPI.Models.Facture", "Facture")
                        .WithMany("Paiements")
                        .HasForeignKey("FactureId");

                    b.HasOne("ComptabiliteAPI.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId");

                    b.Navigation("CompteBancaire");

                    b.Navigation("Facture");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.ProduitService", b =>
                {
                    b.HasOne("ComptabiliteAPI.Models.Entreprise", null)
                        .WithMany("ProduitServices")
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComptabiliteAPI.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.Utilisateur", b =>
                {
                    b.HasOne("ComptabiliteAPI.Models.Abonnement", "Abonnement")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("AbonnementId");

                    b.HasOne("ComptabiliteAPI.Models.Utilisateur", "CreePar")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("CreeParId");

                    b.HasOne("ComptabiliteAPI.Models.Entreprise", "DefaultEntreprise")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("DefaultEntrepriseId");

                    b.Navigation("Abonnement");

                    b.Navigation("CreePar");

                    b.Navigation("DefaultEntreprise");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.Abonnement", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.Entreprise", b =>
                {
                    b.Navigation("Factures");

                    b.Navigation("ProduitServices");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.Facture", b =>
                {
                    b.Navigation("FactureDetails");

                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("ComptabiliteAPI.Models.Utilisateur", b =>
                {
                    b.Navigation("ComptesBancaires");

                    b.Navigation("Entreprises");

                    b.Navigation("Utilisateurs");
                });
#pragma warning restore 612, 618
        }
    }
}
